version: 0.2

env:
  variables:
    BUCKET: 'case-consulting-website-code-dev'
    SAM_CLI_TELEMETRY: 0

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Entering install phase
      - apt-get update -y
      - node --version
      - npm --version
      - python --version
      - pip --version
      - aws --version
      - pip install --user aws-sam-cli
      - sam --version
      - npm ci
      - (cd apply && npm ci)
      - (cd upload && npm ci)
      - (cd workable && npm ci)
    finally:
      - echo Completed install
  pre_build:
    commands:
      - echo Entering pre_build phase
      - npm run precommit
    finally:
      - echo Completed pre_build
  build:
    commands:
      - echo Entering build phase
      - sam build
      - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file packaged.yaml
    finally:
      - echo Completed build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - packaged.yaml
